### ISSUE TITLE
Metrics to use are not clear enough to filter out what can be discarded

### ISSUE THREAD

**Issue by sglavoie** [openspending/audit-for-migration-2020#1]
When I audit the OpenSpending database, I want to have a (mostly) programmable way of knowing what is going to be useful or not based on simple metrics so I can focus on looking more closely at the tables that are important and will not have to manually go through a bunch of tables that serve no purpose or don't meet specific criteria based on known metrics.

## Acceptance

* [ ] Metrics are defined to quickly filter out most of the tables in the database that we can safely discard.

## Tasks

* [ ] Evaluate proposed metrics, then approve or reject them.
* [ ] Come up with additional/better metrics to dispose of data that won't be useful.
* [ ] Determine ownership of tables as this will help in knowing what's being used by whom. (Part of Epic https://github.com/openspending/openspending/issues/1480).

## Analysis

Some metrics I think could be used or tweaked:

* Any table matching the patterns `test`, `fdptest` or `teste` anywhere in the table name correspond to test data. This is highlighted by simply checking for the pattern `test`.
* Tables matching the regular expression `_v\d` (i.e., `_v1`, `_v2`, etc.) are not useful.
* Tables where the column `Row Count` matches the same number in the column `seq_tup_read` on the same row mean that data was inserted and never accessed again (in other words, dumped there and never actually used).
* Tables with 10 or less rows are too small to contain anything useful, especially if they are not being accessed.
* All empty tables are discarded.
* Any table with `idx_scan = 0` means it was never used. Some tables are duplicates and only one of them may be returning results to clients, so the others with zero read access can be discarded, especially if they are of the same size or lower than the table being actively used.
* Because `idx_scan` tells us about how many times a given table was used, we can probably ascertain the relative importance of tables based on how much they are accessed. As a quick guide, 319 tables have been accessed more than 100,000 times out of 8,233 tables, 1,501 tables have been accessed at least once up to 1,000 times and 5,914 tables have not been accessed at all.
* Filtering larger tables based on the uniqueness of row count and/or size in bytes may also prove useful: it's very unlikely that two huge tables will store the exact same number of bytes, so we can eliminate duplicates in this way.

If we have a list of clients/governments that we know are using OpenSpending (by knowing the ownership of each table), it could also help in filtering out anything that doesn't belong to that list.

### Technique for applying the metrics

So far, I have used conditional formatting based on colors because we can filter by colors in Google Sheets: if the tables to discard have color, then selecting `Filter by Color > Fill Color > White` will show only the tables we are interested in keeping.

----
/cc @rufuspollock

**Comment by rufuspollock** [comment]
@sglavoie don't use color formatting in the spreadsheet - have a separate column.

Again please trying and get more succinct in your issues (and even the job story) and more precise e.g. 

### Title

> Metrics to use are not clear enough to filter out what can be discarded

=> Get list of datasets we will migrate

Comment: selection criteria (metrics) are just a means to the end of selecting what to keep. Make that clear in the title.

### Job story

> When I audit the OpenSpending database, I want to have a (mostly) programmable way of knowing what is going to be useful or not based on simple metrics so I can focus on looking more closely at the tables that are important and will not have to manually go through a bunch of tables that serve no purpose or don't meet specific criteria based on known metrics.

JS1: When I select what datasets to migrate (keep) I want criteria to use so that I can (partially) automate the selection process

And behind that i have this bigger job story which is the main one:

JS0: When migrating to new OpenSpending setup I want to only keep those datasets that "real" and "important" (and discard all the test/random datasets) so that we reduce work and have a cleaner future setup

**Comment by rufuspollock** [comment]
@sglavoie i would also encourage you to keep all issues in the main openspending repo so we have one place for stuff. (You can transfer issues with the transfer issue function at top right)
